window.FracaGalleryData = {
  beds: [
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-1.jpg', title: '_211[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-2.jpg', title: '_32[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-3.JPG', title: '104', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-4.JPG', title: '105', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-5.png', title: '105.JPG', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-6.jpg', title: '1-8-m-Podw-jne-ko-Tatami-Pok-j-Mistrza-ku-Sypialni-Proste-Nowoczesne-ko-CE.jpg_640x640[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-7.jpg', title: '3a_b9a31[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-8.jpg', title: '825730fc3d729f71d576c003294a4c3c[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-9.JPG', title: 'BED 3', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-10.jpg', title: 'bed_ruler(l)[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-11.png', title: 'bed2.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-12.png', title: 'bed3.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-13.png', title: 'bed4.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-14.png', title: 'bed5.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-15.jpg', title: 'bed6.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-16.jpg', title: 'bed7.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-17.jpg', title: 'bed8.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-18.png', title: 'bed9.png', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-19.jpg', title: 'BGFB', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-20.jpg', title: 'BS-002[1]', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-21.jpg', title: 'CDSC', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-22.jpg', title: 'fddhjgfdsda', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-23.jpg', title: 'FDE', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-24.jpg', title: 'Image_1759749676156', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-25.png', title: 'IMG-20250503-WA0002', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-26.png', title: 'IMG-20250804-WA0002', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-27.png', title: 'LBO44-Photoroom (73)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-28.png', title: 'LBO44-Photoroom (77)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-29.png', title: 'LBO44-Photoroom (83)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-30.png', title: 'LBO44-Photoroom (88)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-31.png', title: 'LBO44-Photoroom (89)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-32.png', title: 'LBO44-Photoroom (90)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-33.jpg', title: 'VBGVGV', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-34.jpg', title: 'VCF', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-35.jpg', title: 'VGH', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-36.jpg', title: 'VVC', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-37.png', title: 'white-Photoroom (68)', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-38.jpg', title: 'xvb xcgfbvdczxf', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-39.png', title: 'bed-furniture-01', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-40.png', title: 'bed-furniture-02', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-41.png', title: 'bed-furniture-03', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-42.png', title: 'bed-furniture-04', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-43.png', title: 'bed-furniture-05', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-44.png', title: 'bed-furniture-06', desc: '' },
  ],
  coffeeTables: [
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-1.JPG', title: 'CT-10', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-5.png', title: 'E1', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-5.png', title: 'E2', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-5.png', title: 'E3', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-5.png', title: 'E4', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-6.png', title: 'E6', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-7.png', title: 'E7', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-8.png', title: 'E8', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-9.png', title: 'LBO44-Photoroom (96)', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-10.JPG', title: 'mngff', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-11.JPG', title: 'ponbty', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-12.JPG', title: 'pp', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-13.jpg', title: 'Queen-Anne-Table1[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-14.png', title: 'Screenshot 2023-03-03 at 10-03-26 table design - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-15.png', title: 'Screenshot 2024-03-06 at 10-18-13 round coffee table - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-16.png', title: 'Screenshot 2024-03-06 at 10-22-20 round coffee table - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-17.png', title: 'Screenshot 2024-03-06 at 12-47-10 glass round coffee table with middle stand - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-18.jpg', title: 'Serta-Upholstery-Coffee-Table-Set[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-19.jpg', title: 'Sierra-Mission-Medium-Oak-Finish-Coffee-Table-P16252160[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-20.jpg', title: 'William-Sheppee-Binks-Coffee-Table[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-21.png', title: 'coffee-furniture-01', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-22.png', title: 'coffee-furniture-02', desc: '' },
  ],
  diningSets: [
    { src: 'IMAGES/DINING SETS/Dining-Set-1.jpg', title: '0002540_5-piece-dining-table-set-cherry-finish[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-23.jpg', title: '1_37_1049[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-24.jpg', title: '1_37_243_1_1201_1_1186[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-4.jpg', title: '1345[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-5.jpg', title: '1390-76-Set[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-6.jpg', title: '1609bf9ba2e6eedd5b8964b6b0089108[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-7.jpg', title: '1713-15-8[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-8.jpg', title: '19209_orig[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-9.jpg', title: '200772514165063049[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-10.jpg', title: '217_1[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-11.jpg', title: '5300[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-12.jpg', title: '6-seater-dining-table-500x500[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-13.jpg', title: '781759[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-14.jpg', title: '91nysJL9lTL._SL1500_[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-15.jpg', title: 'aria-espresso-dark-wood-square-and-danni-dining-set-23[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-16.jpg', title: 'Atlantic-Furniture-Montego-Bay-5-Piece-Dining-Set[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-17.jpg', title: 'b63447be3740885663e4043a6c9531b4[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-18.jpg', title: 'BARISTA_195cm_DT_with_8_Roma_Chairs[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-19.jpg', title: 'black-dining-table-set-for-6-small-black-glass-dining-table-set-square-black-dining-table-set-black-and-grey-dining-table-set[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-20.jpg', title: 'boyer-black-and-cherry-wood-dining-table-set-6[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-21.jpg', title: 'c53349f3439d348c447ff3a662470f37--round-dining-tables-round-pedestal-tables[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-22.jpg', title: 'captivating-black-round-kitchen-tables-dining-round-table-sets-home-design-interior-exterior-kitchen-cheapjpg[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-23.jpg', title: 'CH2', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-24.jpg', title: 'CH3', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-25.jpg', title: 'ch-may-wooden-dining-room[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-26.jpg', title: 'Copy (2) of ch_p7[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-27.jpg', title: 'Copy (2) of sh_p4[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-28.jpg', title: 'Copy (3) of ch_p8[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-29.jpg', title: 'Copy (3) of sh_p4[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-30.jpg', title: 'Copy of ch_p7[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-31.jpg', title: 'Copy of ch_p8[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-32.jpg', title: 'Copy of sh_p5[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-33.JPG', title: 'dd', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-34.JPG', title: 'ddd', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-35.jpg', title: 'dining[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-36.jpg', title: 'Diningroom-001-Alex[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-37.jpg', title: 'dining-room-table-chairs-fresh-with-images-of-dining-room-concept-new-in-gallery[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-38.jpg', title: 'dr_rm_savona_brown~Sofia-Vergara-Savona-Chocolate-5-Pc-Rectangle-Dining-Room[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-39.png', title: 'H2', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-40.png', title: 'H3', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-41.png', title: 'H4', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-42.png', title: 'H5', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-43.png', title: 'H6', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-44.png', title: 'H7', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-45.png', title: 'IMG_20240105_090210', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-46.png', title: 'LBO44-Photoroom - 2025-10-06T125721.845', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-47.png', title: 'LBO44-Photoroom (68)', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-48.jpg', title: 'round-kitchen-table-and-chair-sets-kitchen-table-sets-kmart[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-49.jpg', title: 'spin_prod_1287870812[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-50.png', title: 'dining-furniture-01', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-51.png', title: 'dining-furniture-02', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-52.png', title: 'dining-furniture-03', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-53.png', title: 'dining-furniture-04', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-54.png', title: 'dining-furniture-05', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-55.png', title: 'dining-furniture-06', desc: '' },
  ],
  dressingMirrors: [
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-1.JPG', title: 'DM-41', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-2.JPG', title: 'DM-42', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-3.JPG', title: 'DM-44', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-4.JPG', title: 'DM-50', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-5.JPG', title: 'DM-53', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-6.jpg', title: 'DM-54', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-7.JPG', title: 'DM-55', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-8.jpg', title: 'fym-721-with-mirror-dresser-500x500[1]', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-9.png', title: 'LBO44-Photoroom (95)', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-10.png', title: 'M1', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-11.png', title: 'M2', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-12.png', title: 'dressing-mirror-furniture-01', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-13.png', title: 'dressing-mirror-furniture-02', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-14.png', title: 'dressing-mirror-furniture-03', desc: '' },
  ],
  churchFurniture: [
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-1.png', title: 'B1', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-2.png', title: 'B2', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-3.png', title: 'B3', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-4.png', title: 'B4', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-5.png', title: 'B5', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-6.png', title: 'B6', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-7.png', title: 'Y2', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-8.png', title: 'Y3', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-9.png', title: 'EIGHT', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-10.png', title: 'ELEVEN', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-11.jpg', title: 'FIVE', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-12.jpg', title: 'FOUR', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-13.png', title: 'NINE', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-14.jpg', title: 'ONE', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-15.png', title: 'SEVEN', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-16.JPG', title: 'SIX', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-17.png', title: 'TEN', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-18.jpg', title: 'THREE', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/Church-Furniture-19.jpg', title: 'TWO', desc: '' },
  ],
  utilityChairs: [
    { src: 'IMAGES/UTILITY CHAIRS/Chair-1.JPG', title: '33', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-2.jpg', title: '4-seater-waiting-chair-500x500-1', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-3.jpg', title: '53_20161911[1]', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-4.JPG', title: '62', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-5.png', title: 'A14', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-6.png', title: 'A16', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-7.png', title: 'A33', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-9.png', title: 'A68', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-9.png', title: 'A8', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-10.jpg', title: 'BHJF', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-11.jpg', title: 'BVBN', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-12.jpg', title: 'CFGG', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-13.jpg', title: 'DFFDS', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-14.jpg', title: 'DFG', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-15.jpg', title: 'DFGH', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-16.jpg', title: 'DFGYHJ', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-17.jpg', title: 'EFDG', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-18.jpg', title: 'FCFG', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-19.jpg', title: 'FGHFG', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-20.jpg', title: 'Figueras�203100�20Mauro�20-�20Ergonomic�20benches�20for�20airports�20590px[1]', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-21.jpg', title: 'HJKL', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-22.jpg', title: 'HYUJK', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-23.jpg', title: 'Image_1759749820653', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-24.JPG', title: 'l', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-25.jpg', title: 'LBO44-Photoroom (5)', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-26.jpg', title: 'LBO44-Photoroom (6)', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-27.jpg', title: 'LBO44-Photoroom (7)', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-28.JPG', title: 'LINK 13', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-29.jpg', title: 'LINK 3', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-30.JPG', title: 'LINK CHAIR 2', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-31.JPG', title: 'LK', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-32.jpg', title: 'NHGF', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-33.jpg', title: 'p-zoom[1]', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-34.jpg', title: 'VGHJ', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-35.jpg', title: 'Visitors chair', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-36.png', title: 'white-Photoroom (67)', desc: '' },
    { src: 'IMAGES/UTILITY CHAIRS/Chair-37.jpg', title: 'XSCV', desc: '' },
  ],
  wardrobes: [
    { src: 'IMAGES/WARDROBES/Wardrobe-21.png', title: '3-door-wardrobe-500x500[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-2.jpg', title: '4-030[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-3.jpg', title: '4-door-with-mirror[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-4.jpg', title: '7011671012_2dr_coffee[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-5.jpg', title: '701-167-1016[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-6.jpg', title: '71', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-7.jpg', title: '71zOKvbqJ9L', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-8.jpg', title: '930f0cb5caf002108990d14a1a89be72', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-9.jpg', title: 'BG', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-10.jpg', title: 'black-glass-chest-of-drawers-p41179-31306_zoom[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-11.JPG', title: 'CH3', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-12.jpg', title: 'CHARLES_1_DOOR_6_DRAWER_CHEST[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-13.JPG', title: 'CHEST OF DRAWERS', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-14.jpg', title: 'CV CC', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-15.jpg', title: 'DFG', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-16.jpg', title: 'DFRT', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-17.jpg', title: 'hemnes-chest-of-6-drawers-skoyro-kafe-0[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-18.jpg', title: 'HGYU', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-19.jpg', title: 'Magnussen_Ashby_8_Drawer_Chest_2[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-20.jpg', title: 'pine-furniture-pine-bedroom-furniture-parque-royal-pine-chest-of-drawers[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-21.png', title: 'W1', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-22.png', title: 'W2', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-23.png', title: 'W3', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-24.png', title: 'W4', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-25.jpg', title: 'ZSER', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-26.png', title: 'wardrobe-furniture-01', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-27.png', title: 'wardrobe-furniture-02', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-28.png', title: 'wardrobe-furniture-03', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-29.png', title: 'wardrobe-furniture-04', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-30.png', title: 'wardrobe-furniture-05', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-31.png', title: 'wardrobe-furniture-06', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-32.png', title: 'wardrobe-furniture-07', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-33.png', title: 'wardrobe-furniture-08', desc: '' },
  ],
  sofaSets: [
    { src: 'IMAGES/SOFA SETS/Sofa-1.png', title: 'S1', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-6.png', title: 'S10', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S11', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-6.png', title: 'S2', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S3', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-6.png', title: 'S4', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S5', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S7', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S8', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S9', desc: '' },
  ],
  conferenceTables: [
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-1.png', title: 'F1', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-6.png', title: 'F10', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-6.png', title: 'F2', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-6.png', title: 'F3', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-6.png', title: 'F4', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-6.png', title: 'F5', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-7.jpg', title: 'F6', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-8.png', title: 'F8', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-9.png', title: 'F9', desc: '' },
  ],
  conferenceChairs: [
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-1.png', title: 'A27', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-2.png', title: 'A37', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-3.png', title: 'A71', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-4.png', title: 'A73', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-5.png', title: 'A74', desc: '' },
  ],
  workStations: [
    { src: 'IMAGES/WORK STATIONS/Workstation-1.png', title: 'I1', desc: '' },
    { src: 'IMAGES/WORK STATIONS/Workstation-2.png', title: 'I2', desc: '' },
    { src: 'IMAGES/WORK STATIONS/Workstation-3.png', title: 'I3', desc: '' },
    { src: 'IMAGES/WORK STATIONS/Workstation-4.png', title: 'I4', desc: '' },
    { src: 'IMAGES/WORK STATIONS/Workstation-5.png', title: 'I5', desc: '' },
  ],
  filingCabinets: [
    { src: 'IMAGES/FILING CABINETS/Cabinet-1.png', title: 'G1', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-8.png', title: 'G10', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-5.png', title: 'G11', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-8.png', title: 'G2', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-5.png', title: 'G3', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-8.png', title: 'G4', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-7.jpg', title: 'G5', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-8.png', title: 'G6', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-9.jpg', title: 'G8', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-10.png', title: 'G9', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-11.jpeg', title: 'WhatsApp Image 2026-07-25 at 14.30.36', desc: '' },
  ],
  studentSets: [
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-1.jpeg', title: 'WhatsApp Image 2026-07-25 at 14.30.37', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-5.png', title: 'X1', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-5.png', title: 'X2', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-5.png', title: 'X3', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-5.png', title: 'X4', desc: '' },
  ],
  entertainmentUnits: [
    { src: 'IMAGES/ENTERTAINMENT UNITS/Entertainment-Unit-1.png', title: 'J1', desc: '' },
    { src: 'IMAGES/ENTERTAINMENT UNITS/Entertainment-Unit-2.png', title: 'J2', desc: '' },
    { src: 'IMAGES/ENTERTAINMENT UNITS/Entertainment-Unit-3.png', title: 'J3', desc: '' },
  ],
  executiveOfficeDesks: [
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-1.png', title: 'D10', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-22.png', title: 'D11', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-17.png', title: 'D12', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-18.png', title: 'D13', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-19.png', title: 'D14', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-20.png', title: 'D15', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-21.png', title: 'D16', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-22.png', title: 'D2', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-23.png', title: 'D20', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-10.jpg', title: 'D21', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-11.jpg', title: 'D22', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-12.png', title: 'D23', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-13.jpg', title: 'D24', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-14.jpg', title: 'D25', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-15.jpg', title: 'D26', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-16.png', title: 'D27', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-17.png', title: 'D3', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-18.png', title: 'D4', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-19.png', title: 'D5', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-20.png', title: 'D6', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-21.png', title: 'D7', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-22.png', title: 'D8', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-23.png', title: 'D9', desc: '' },
  ],
  pedestalDesks: [
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-1.png', title: 'P1', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-2.png', title: 'P2', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-3.png', title: 'P3', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-4.png', title: 'P4', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-5.jpg', title: 'P5', desc: '' },
  ],
  receptionDesks: [
    { src: 'IMAGES/RECEPTION DESKS/Reception-Desk-3.png', title: 'P6', desc: '' },
    { src: 'IMAGES/RECEPTION DESKS/Reception-Desk-3.png', title: 'R1', desc: '' },
    { src: 'IMAGES/RECEPTION DESKS/Reception-Desk-3.png', title: 'R2', desc: '' },
  ],
  officeChairs: [
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-1.png', title: 'A1', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-2.png', title: 'A10', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-13.png', title: 'A11', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-4.png', title: 'A12', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-20.png', title: 'A13', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-6.png', title: 'A18', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-7.png', title: 'A19', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-8.png', title: 'A20', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-30.png', title: 'A22', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-10.png', title: 'A23', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-11.png', title: 'A25', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-12.png', title: 'A26', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-13.png', title: 'A3', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-14.png', title: 'A4', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-15.png', title: 'A40', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-16.png', title: 'A46', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-17.png', title: 'A47', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-18.png', title: 'A48', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-19.png', title: 'A49', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-20.png', title: 'A5', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-21.png', title: 'A50', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-22.png', title: 'A51', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-23.png', title: 'A52', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-24.png', title: 'A53', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-25.png', title: 'A54', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-26.png', title: 'A55', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-27.png', title: 'A75', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-28.png', title: 'A76', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-29.png', title: 'A77', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-30.png', title: 'A9', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-31.png', title: 'V', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-32.png', title: 'V1', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-33.png', title: 'V4', desc: '' },
  ],
  visitorsBoardroomChairs: [
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-1.png', title: 'A2', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-1.png', title: 'A21', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-3.png', title: 'A28', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-4.png', title: 'A31', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-16.png', title: 'A32', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-9.png', title: 'A34', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-7.png', title: 'A38', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-8.png', title: 'A39', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-9.png', title: 'A6', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-10.png', title: 'A65', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-11.png', title: 'A66', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-12.png', title: 'A67', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-13.png', title: 'A69', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-14.png', title: 'A70', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-15.jpg', title: 'A72', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-16.png', title: 'C5', desc: '' },
  ],
  linkChairs: [
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-1.png', title: 'C1', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-2.png', title: 'C2', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-3.png', title: 'C3', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-4.png', title: 'C4', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-5.png', title: 'C6', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-6.png', title: 'C7', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-7.png', title: 'C8', desc: '' },
  ],
  catalinaChairs: [
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-1.png', title: 'A15', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-2.png', title: 'A17', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-3.png', title: 'A43', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-4.png', title: 'A44', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-5.png', title: 'A45', desc: '' },
  ],
  churchAssemblyChairs: [
    { src: 'IMAGES/CHURCH & ASSEMBLY CHAIRS/Chair-1.png', title: 'A42', desc: '' },
    { src: 'IMAGES/CHURCH & ASSEMBLY CHAIRS/Chair-2.png', title: 'A7', desc: '' },
  ],
  libraryShelves: [
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-1.png', title: 'T1', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-2.png', title: 'T2', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-3.png', title: 'T3', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-4.png', title: 'T4', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-5.png', title: 'T5', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-6.png', title: 'T6', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-7.png', title: 'T7', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-8.jpeg', title: 'WhatsApp Image 2026-07-25 at 14.30.37 (1)', desc: '' },
  ],
  storageSafes: [
    { src: 'IMAGES/STORAGE SAFES/Safe-1.png', title: 'K4', desc: '' },
    { src: 'IMAGES/STORAGE SAFES/Safe-2.jpeg', title: 'K5', desc: '' },
    { src: 'IMAGES/STORAGE SAFES/Safe-3.png', title: 'K6', desc: '' },
    { src: 'IMAGES/STORAGE SAFES/Safe-4.png', title: 'K7', desc: '' },
  ],
  coatHangers: [
    { src: 'IMAGES/COAT HANGERS/Coat-Hanger-1.png', title: 'K2', desc: '' },
    { src: 'IMAGES/COAT HANGERS/Coat-Hanger-2.jpeg', title: 'WhatsApp Image 2026-08-20 at 13.39.22', desc: '' },
  ],
  shoeRacks: [
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-1.jpg', title: 'shoerack 1', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-2.jpg', title: 'shoerack 2', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-3.jpg', title: 'shoerack 3', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-4.jpg', title: 'shoerack 4', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-5.jpg', title: 'shoerack 5', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-6.jpg', title: 'shoerack', desc: '' },
  ],
  restaurantSeats: [
    { src: 'IMAGES/RESTAURANT SEATS/Seat-1.png', title: 'A35', desc: '' },
    { src: 'IMAGES/RESTAURANT SEATS/Seat-2.png', title: 'A36', desc: '' },
    { src: 'IMAGES/RESTAURANT SEATS/Seat-3.png', title: 'A41', desc: '' },
  ],
  rockingChairs: [
    { src: 'IMAGES/ROCKING CHAIRS/Rocking-Chair-1.png', title: 'A73', desc: '' },
  ],
  benches: [
    { src: 'IMAGES/BENCHES/Bench-1.png', title: 'BENCH', desc: '' },
  ],
  executiveChairs: {
    senior: [
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-1.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-2.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-3.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-4.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-5.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-6.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-7.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-8.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-9.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-10.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-11.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-12.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-13.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-14.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-15.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-16.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-17.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-18.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-19.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-20.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-21.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-22.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-23.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-24.png',
    ],
    orthopedic: [
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-1.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-2.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-3.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-4.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-5.png',
    ],
    lowBack: [
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-1.png',
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-2.png',
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-3.png',
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-4.png',
    ],
    midBack: [
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-1.JPG',
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-2.png',
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-3.png',
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-4.png',
    ],
  }
};

