window.FracaGalleryData = {
  beds: [
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-1.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-2.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-4.JPG', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-5.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-6.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-7.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-8.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-9.JPG', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-11.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-12.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-13.png', title: '', desc: '' },
    {
      title: 'Canopy bedroom set',
      desc: 'Dark wood canopy bed with matching nightstands and bench. Multiple room views.',
      src: 'IMAGES/EXECUTIVE BEDS/Bed-15.jpg',
      variants: [
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-15.jpg', color: '' },
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-16.jpg', color: '' },
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-17.jpg', color: '' },
      ],
    },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-18.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-20.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-21.jpg', title: '', desc: '' },
    {
      title: 'Panel headboard bed',
      desc: 'Wooden frame with inset padded panels. Available in multiple panel colours.',
      src: 'IMAGES/EXECUTIVE BEDS/Bed-43.png',
      variants: [
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-43.png', color: 'White' },
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-38.jpg', color: 'White' },
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-22.jpg', color: 'Charcoal' },
        { src: 'IMAGES/EXECUTIVE BEDS/Bed-44.png', color: 'Dark brown' },
      ],
    },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-23.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-24.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-25.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-26.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-31.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-32.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-35.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-36.jpg', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-39.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-40.png', title: 'Tufted headboard bed', desc: 'Light wood frame with white diamond-tufted headboard.' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-41.png', title: '', desc: '' },
    { src: 'IMAGES/EXECUTIVE BEDS/Bed-42.png', title: '', desc: '' },
  ],
  coffeeTables: [
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-1.JPG', title: 'CT-10', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-2.png', title: 'E1', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-3.png', title: 'E2', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-4.png', title: 'E3', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-5.png', title: 'E4', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-6.png', title: 'E6', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-7.png', title: 'E7', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-8.png', title: 'E8', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-9.png', title: 'LBO44-Photoroom (96)', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-10.JPG', title: 'mngff', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-11.JPG', title: 'ponbty', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-12.JPG', title: 'pp', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-13.jpg', title: 'Queen-Anne-Table1[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-14.png', title: 'Screenshot 2023-03-03 at 10-03-26 table design - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-15.png', title: 'Screenshot 2024-03-06 at 10-18-13 round coffee table - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-16.png', title: 'Screenshot 2024-03-06 at 10-22-20 round coffee table - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-17.png', title: 'Screenshot 2024-03-06 at 12-47-10 glass round coffee table with middle stand - Google Search', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-18.jpg', title: 'Serta-Upholstery-Coffee-Table-Set[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-19.jpg', title: 'Sierra-Mission-Medium-Oak-Finish-Coffee-Table-P16252160[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-20.jpg', title: 'William-Sheppee-Binks-Coffee-Table[1]', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-21.png', title: 'coffee-furniture-01', desc: '' },
    { src: 'IMAGES/COFFEE TABLES/Coffee-Table-22.png', title: 'coffee-furniture-02', desc: '' },
  ],
  diningSets: [
    { src: 'IMAGES/DINING SETS/Dining-Set-1.jpg', title: '0002540_5-piece-dining-table-set-cherry-finish[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-2.jpg', title: '1_37_1049[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-3.jpg', title: '1_37_243_1_1201_1_1186[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-4.jpg', title: '1345[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-5.jpg', title: '1390-76-Set[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-6.jpg', title: '1609bf9ba2e6eedd5b8964b6b0089108[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-7.jpg', title: '1713-15-8[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-8.jpg', title: '19209_orig[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-9.jpg', title: '200772514165063049[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-10.jpg', title: '217_1[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-11.jpg', title: '5300[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-12.jpg', title: '6-seater-dining-table-500x500[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-13.jpg', title: '781759[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-14.jpg', title: '91nysJL9lTL._SL1500_[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-15.jpg', title: 'aria-espresso-dark-wood-square-and-danni-dining-set-23[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-16.jpg', title: 'Atlantic-Furniture-Montego-Bay-5-Piece-Dining-Set[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-17.jpg', title: 'b63447be3740885663e4043a6c9531b4[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-18.jpg', title: 'BARISTA_195cm_DT_with_8_Roma_Chairs[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-19.jpg', title: 'black-dining-table-set-for-6-small-black-glass-dining-table-set-square-black-dining-table-set-black-and-grey-dining-table-set[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-20.jpg', title: 'boyer-black-and-cherry-wood-dining-table-set-6[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-21.jpg', title: 'c53349f3439d348c447ff3a662470f37--round-dining-tables-round-pedestal-tables[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-22.jpg', title: 'captivating-black-round-kitchen-tables-dining-round-table-sets-home-design-interior-exterior-kitchen-cheapjpg[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-23.jpg', title: 'CH2', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-24.jpg', title: 'CH3', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-25.jpg', title: 'ch-may-wooden-dining-room[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-26.jpg', title: 'Copy (2) of ch_p7[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-27.jpg', title: 'Copy (2) of sh_p4[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-28.jpg', title: 'Copy (3) of ch_p8[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-29.jpg', title: 'Copy (3) of sh_p4[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-30.jpg', title: 'Copy of ch_p7[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-31.jpg', title: 'Copy of ch_p8[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-32.jpg', title: 'Copy of sh_p5[2]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-33.JPG', title: 'dd', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-34.JPG', title: 'ddd', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-35.jpg', title: 'dining[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-36.jpg', title: 'Diningroom-001-Alex[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-37.jpg', title: 'dining-room-table-chairs-fresh-with-images-of-dining-room-concept-new-in-gallery[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-38.jpg', title: 'dr_rm_savona_brown~Sofia-Vergara-Savona-Chocolate-5-Pc-Rectangle-Dining-Room[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-39.png', title: 'H2', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-40.png', title: 'H3', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-41.png', title: 'H4', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-42.png', title: 'H5', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-43.png', title: 'H6', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-44.png', title: 'H7', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-45.png', title: 'IMG_20240105_090210', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-46.png', title: 'LBO44-Photoroom - 2025-10-06T125721.845', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-47.png', title: 'LBO44-Photoroom (68)', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-48.jpg', title: 'round-kitchen-table-and-chair-sets-kitchen-table-sets-kmart[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-49.jpg', title: 'spin_prod_1287870812[1]', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-50.png', title: 'dining-furniture-01', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-51.png', title: 'dining-furniture-02', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-52.png', title: 'dining-furniture-03', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-53.png', title: 'dining-furniture-04', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-54.png', title: 'dining-furniture-05', desc: '' },
    { src: 'IMAGES/DINING SETS/Dining-Set-55.png', title: 'dining-furniture-06', desc: '' },
  ],
  dressingMirrors: [
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-1.JPG', title: 'DM-41', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-2.JPG', title: 'DM-42', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-3.JPG', title: 'DM-44', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-4.JPG', title: 'DM-50', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-5.JPG', title: 'DM-53', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-6.jpg', title: 'DM-54', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-7.JPG', title: 'DM-55', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-8.jpg', title: 'fym-721-with-mirror-dresser-500x500[1]', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-9.png', title: 'LBO44-Photoroom (95)', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-10.png', title: 'M1', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-11.png', title: 'M2', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-12.png', title: 'dressing-mirror-furniture-01', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-13.png', title: 'dressing-mirror-furniture-02', desc: '' },
    { src: 'IMAGES/DRESSING MIRRORS/Mirror-14.png', title: 'dressing-mirror-furniture-03', desc: '' },
  ],
  churchFurniture: {
    chairs: [
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Assembly-Chair-1.png', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Assembly-Chair-2.png', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Chair-CF-5.png', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Chair-CF-6.png', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-1.JPG', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-2.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-3.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-4.JPG', title: '', desc: '' },
    {
      title: 'Wood-arm guest chair',
      desc: 'Black tubular frame with wood arm caps. Available in multiple upholstery colours.',
      src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-5.png',
      variants: [
        { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-5.png', color: 'Navy' },
        { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-6.png', color: 'Brown' },
      ],
    },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-7.png', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-8.png', title: '', desc: '' },
    {
      title: 'Armless assembly chair',
      desc: 'Separate seat and back on a black tubular frame. Available in multiple upholstery colours.',
      src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-9.png',
      variants: [
        { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-9.png', color: 'Brown' },
        { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-12.jpg', color: 'Navy' },
      ],
    },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-10.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-11.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-13.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-14.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-15.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-16.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-17.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-18.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-19.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-20.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-21.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-22.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-23.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-24.JPG', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-25.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-26.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-27.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-28.JPG', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-29.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-30.JPG', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-31.JPG', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-32.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-33.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-34.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-35.jpg', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-36.png', title: '', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/CHAIRS/Utility-Chair-37.jpg', title: '', desc: '' },
    ],
    pews: [
    { src: 'IMAGES/CHURCH FURNITURE/PEWS/Pew-1.png', title: 'Pew 1', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PEWS/Pew-2.png', title: 'Pew 2', desc: '' },
  ],
  pulpits: [
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-3.png', title: 'Pulpit 1', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-4.png', title: 'Pulpit 2', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-7.png', title: 'Pulpit 3', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-8.png', title: 'Pulpit 4', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-9.png', title: 'Pulpit 5', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-10.png', title: 'Pulpit 6', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-11.jpg', title: 'Pulpit 7', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-12.jpg', title: 'Pulpit 8', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-14.jpg', title: 'Pulpit 10', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-15.png', title: 'Pulpit 11', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-16.JPG', title: 'Pulpit 12', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-17.png', title: 'Pulpit 13', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-18.jpg', title: 'Pulpit 14', desc: '' },
    { src: 'IMAGES/CHURCH FURNITURE/PULPITS/Pulpit-19.jpg', title: 'Pulpit 15', desc: '' },
    ],
  },

  wardrobes: [
    { src: 'IMAGES/WARDROBES/Wardrobe-1.png', title: '3-door-wardrobe-500x500[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-2.jpg', title: '4-030[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-3.jpg', title: '4-door-with-mirror[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-4.jpg', title: '7011671012_2dr_coffee[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-5.jpg', title: '701-167-1016[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-6.jpg', title: '71', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-7.jpg', title: '71zOKvbqJ9L', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-8.jpg', title: '930f0cb5caf002108990d14a1a89be72', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-9.jpg', title: 'BG', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-10.jpg', title: 'black-glass-chest-of-drawers-p41179-31306_zoom[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-11.JPG', title: 'CH3', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-12.jpg', title: 'CHARLES_1_DOOR_6_DRAWER_CHEST[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-13.JPG', title: 'CHEST OF DRAWERS', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-14.jpg', title: 'CV CC', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-15.jpg', title: 'DFG', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-16.jpg', title: 'DFRT', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-17.jpg', title: 'hemnes-chest-of-6-drawers-skoyro-kafe-0[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-18.jpg', title: 'HGYU', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-19.jpg', title: 'Magnussen_Ashby_8_Drawer_Chest_2[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-20.jpg', title: 'pine-furniture-pine-bedroom-furniture-parque-royal-pine-chest-of-drawers[1]', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-21.png', title: 'W1', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-22.png', title: 'W2', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-23.png', title: 'W3', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-24.png', title: 'W4', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-25.jpg', title: 'ZSER', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-26.png', title: 'wardrobe-furniture-01', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-27.png', title: 'wardrobe-furniture-02', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-28.png', title: 'wardrobe-furniture-03', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-29.png', title: 'wardrobe-furniture-04', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-30.png', title: 'wardrobe-furniture-05', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-31.png', title: 'wardrobe-furniture-06', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-32.png', title: 'wardrobe-furniture-07', desc: '' },
    { src: 'IMAGES/WARDROBES/Wardrobe-33.png', title: 'wardrobe-furniture-08', desc: '' },
  ],
  sofaSets: [
    { src: 'IMAGES/SOFA SETS/Sofa-1.png', title: 'S1', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-2.png', title: 'S10', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-3.png', title: 'S11', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-4.png', title: 'S2', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-5.png', title: 'S3', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-6.png', title: 'S4', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-7.png', title: 'S5', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-8.png', title: 'S7', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-9.png', title: 'S8', desc: '' },
    { src: 'IMAGES/SOFA SETS/Sofa-10.png', title: 'S9', desc: '' },
  ],
  conferenceTables: [
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-1.png', title: 'F1', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-2.png', title: 'F10', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-3.png', title: 'F2', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-4.png', title: 'F3', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-5.png', title: 'F4', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-6.png', title: 'F5', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-7.jpg', title: 'F6', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-8.png', title: 'F8', desc: '' },
    { src: 'IMAGES/CONFERENCE TABLES/Conference-Table-9.png', title: 'F9', desc: '' },
  ],
  conferenceChairs: [
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-1.png', title: 'A27', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-2.png', title: 'A37', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-3.png', title: 'A71', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-4.png', title: 'A73', desc: '' },
    { src: 'IMAGES/CONFERENCE CHAIRS/Conference-Chair-5.png', title: 'A74', desc: '' },
  ],
  workStations: [
    { src: 'IMAGES/WORK STATIONS/Workstation-1.png', title: '', desc: '' },
    { src: 'IMAGES/WORK STATIONS/Workstation-2.png', title: '', desc: '' },
    { src: 'IMAGES/WORK STATIONS/Workstation-3.png', title: '', desc: '' },
    {
      title: 'L-shaped privacy workstation',
      desc: 'Corner desk with privacy panels and a locking three-drawer pedestal. Extra product photos included.',
      src: 'IMAGES/WORK STATIONS/Workstation-4.png',
      variants: [
        { src: 'IMAGES/WORK STATIONS/Workstation-4.png', color: '' },
        { src: 'IMAGES/WORK STATIONS/Workstation-5.png', color: '' },
      ],
    },
  ],
  filingCabinets: [
    { src: 'IMAGES/FILING CABINETS/Cabinet-1.png', title: 'G1', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-2.png', title: 'G10', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-3.png', title: 'G11', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-4.png', title: 'G2', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-5.png', title: 'G3', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-6.png', title: 'G4', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-7.jpg', title: 'G5', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-8.png', title: 'G6', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-9.jpg', title: 'G8', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-10.png', title: 'G9', desc: '' },
    { src: 'IMAGES/FILING CABINETS/Cabinet-11.jpeg', title: 'WhatsApp Image 2026-07-25 at 14.30.36', desc: '' },
  ],
  studentSets: [
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-1.jpeg', title: '', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-2.png', title: '', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-3.png', title: '', desc: '' },
    { src: 'IMAGES/STUDENTS SETS/Student-Desk-4.png', title: '', desc: '' },
  ],
  entertainmentUnits: [
    { src: 'IMAGES/ENTERTAINMENT UNITS/Entertainment-Unit-1.png', title: 'J1', desc: '' },
    { src: 'IMAGES/ENTERTAINMENT UNITS/Entertainment-Unit-2.png', title: 'J2', desc: '' },
    { src: 'IMAGES/ENTERTAINMENT UNITS/Entertainment-Unit-3.png', title: 'J3', desc: '' },
  ],
  executiveOfficeDesks: [
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-1.png', title: 'D10', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-2.png', title: 'D11', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-3.png', title: 'D12', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-4.png', title: 'D13', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-5.png', title: 'D14', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-6.png', title: 'D15', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-7.png', title: 'D16', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-8.png', title: 'D2', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-9.png', title: 'D20', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-10.jpg', title: 'D21', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-11.jpg', title: 'D22', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-12.png', title: 'D23', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-13.jpg', title: 'D24', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-14.jpg', title: 'D25', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-15.jpg', title: 'D26', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-16.png', title: 'D27', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-17.png', title: 'D3', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-18.png', title: 'D4', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-19.png', title: 'D5', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-20.png', title: 'D6', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-21.png', title: 'D7', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-22.png', title: 'D8', desc: '' },
    { src: 'IMAGES/EXECUTIVE OFFICE DESKS/Desk-23.png', title: 'D9', desc: '' },
  ],
  pedestalDesks: [
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-1.png', title: 'P1', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-2.png', title: 'P2', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-3.png', title: 'P3', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-4.png', title: 'P4', desc: '' },
    { src: 'IMAGES/PEDESTAL DESKS/Pedestal-Desk-5.jpg', title: 'P5', desc: '' },
  ],
  receptionDesks: [
    { src: 'IMAGES/RECEPTION DESKS/Reception-Desk-1.png', title: 'P6', desc: '' },
    { src: 'IMAGES/RECEPTION DESKS/Reception-Desk-2.png', title: 'R1', desc: '' },
    { src: 'IMAGES/RECEPTION DESKS/Reception-Desk-3.png', title: 'R2', desc: '' },
  ],
  officeChairs: [
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-1.png', title: 'A1', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-2.png', title: 'A10', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-3.png', title: 'A11', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-4.png', title: 'A12', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-5.png', title: 'A13', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-6.png', title: 'A18', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-7.png', title: 'A19', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-8.png', title: 'A20', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-9.png', title: 'A22', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-10.png', title: 'A23', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-11.png', title: 'A25', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-12.png', title: 'A26', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-13.png', title: 'A3', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-14.png', title: 'A4', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-15.png', title: 'A40', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-16.png', title: 'A46', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-17.png', title: 'A47', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-18.png', title: 'A48', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-19.png', title: 'A49', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-20.png', title: 'A5', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-21.png', title: 'A50', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-22.png', title: 'A51', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-23.png', title: 'A52', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-24.png', title: 'A53', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-25.png', title: 'A54', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-26.png', title: 'A55', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-27.png', title: 'A75', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-28.png', title: 'A76', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-29.png', title: 'A77', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-30.png', title: 'A9', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-31.png', title: 'V', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-32.png', title: 'V1', desc: '' },
    { src: 'IMAGES/OFFICE CHAIRS/Office-Chair-33.png', title: 'V4', desc: '' },
  ],
  visitorsBoardroomChairs: [
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-1.png', title: 'A2', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-2.png', title: 'A21', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-3.png', title: 'A28', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-4.png', title: 'A31', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-5.png', title: 'A32', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-6.png', title: 'A34', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-7.png', title: 'A38', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-8.png', title: 'A39', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-9.png', title: 'A6', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-10.png', title: 'A65', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-11.png', title: 'A66', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-12.png', title: 'A67', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-13.png', title: 'A69', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-14.png', title: 'A70', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-15.jpg', title: 'A72', desc: '' },
    { src: 'IMAGES/VISITORS & BOARDROOM CHAIRS/Chair-16.png', title: 'C5', desc: '' },
  ],
  linkChairs: [
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-1.png', title: 'C1', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-2.png', title: 'C2', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-3.png', title: 'C3', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-4.png', title: 'C4', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-5.png', title: 'C6', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-6.png', title: 'C7', desc: '' },
    { src: 'IMAGES/LINK CHAIRS/Link-Chair-7.png', title: 'C8', desc: '' },
  ],
  catalinaChairs: [
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-1.png', title: 'A15', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-2.png', title: 'A17', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-3.png', title: 'A43', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-4.png', title: 'A44', desc: '' },
    { src: 'IMAGES/CATALINA CHAIRS/Catalina-Chair-5.png', title: 'A45', desc: '' },
  ],
  libraryShelves: [
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-1.png', title: 'T1', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-2.png', title: 'T2', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-3.png', title: 'T3', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-4.png', title: 'T4', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-5.png', title: 'T5', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-6.png', title: 'T6', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-7.png', title: 'T7', desc: '' },
    { src: 'IMAGES/LIBRARY & SUPERMARKET SHELVES/Shelf-8.jpeg', title: 'WhatsApp Image 2026-07-25 at 14.30.37 (1)', desc: '' },
  ],
  storageSafes: [
    { src: 'IMAGES/STORAGE SAFES/Safe-1.png', title: 'K4', desc: '' },
    { src: 'IMAGES/STORAGE SAFES/Safe-2.jpeg', title: 'K5', desc: '' },
    { src: 'IMAGES/STORAGE SAFES/Safe-3.png', title: 'K6', desc: '' },
    { src: 'IMAGES/STORAGE SAFES/Safe-4.png', title: 'K7', desc: '' },
  ],
  coatHangers: [
    { src: 'IMAGES/COAT HANGERS/Coat-Hanger-1.png', title: 'K2', desc: '' },
    { src: 'IMAGES/COAT HANGERS/Coat-Hanger-2.jpeg', title: 'WhatsApp Image 2026-08-20 at 13.39.22', desc: '' },
  ],
  shoeRacks: [
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-1.jpg', title: 'shoerack 1', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-2.jpg', title: 'shoerack 2', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-3.jpg', title: 'shoerack 3', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-4.jpg', title: 'shoerack 4', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-5.jpg', title: 'shoerack 5', desc: '' },
    { src: 'IMAGES/Shoe Racks/Shoe-Rack-6.jpg', title: 'shoerack', desc: '' },
  ],
  restaurantSeats: [
    { src: 'IMAGES/RESTAURANT SEATS/Seat-1.png', title: 'A35', desc: '' },
    { src: 'IMAGES/RESTAURANT SEATS/Seat-2.png', title: 'A36', desc: '' },
    { src: 'IMAGES/RESTAURANT SEATS/Seat-3.png', title: 'A41', desc: '' },
  ],
  rockingChairs: [
    { src: 'IMAGES/ROCKING CHAIRS/Rocking-Chair-1.png', title: 'A73', desc: '' },
  ],
  benches: [
    { src: 'IMAGES/BENCHES/Bench-1.png', title: 'BENCH', desc: '' },
  ],
  executiveChairs: {
    senior: [
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-1.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-2.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-3.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-4.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-5.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-6.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-7.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-8.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-9.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-10.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-11.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-12.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-13.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-14.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-15.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-16.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-17.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-18.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-19.jpg',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-20.JPG',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-21.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-22.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-23.png',
      'IMAGES/EXECUTIVE CHAIRS/SENIOR EXECUTIVE HIGH BACK CHAIRS/Chair-24.png',
    ],
    orthopedic: [
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-1.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-2.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-3.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-4.png',
      'IMAGES/EXECUTIVE CHAIRS/ORTHOPEDIC HIGH BACK CHAIRS/Chair-5.png',
    ],
    lowBack: [
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-1.png',
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-2.png',
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-3.png',
      'IMAGES/EXECUTIVE CHAIRS/LOW BACK CHAIRS/Chair-4.png',
    ],
    midBack: [
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-1.JPG',
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-2.png',
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-3.png',
      'IMAGES/EXECUTIVE CHAIRS/MID BACK CHAIRS/Chair-4.png',
    ],
  },
  bags: {
    ladiesHandbagsLb001: [
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bag-8.png', title: 'ladies-hand-bag-8', desc: '' },
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bag-9.png', title: 'ladies-hand-bag-9', desc: '' },
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bag-10.png', title: 'ladies-hand-bag-10', desc: '' },
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bag-11.png', title: 'ladies-hand-bag-11', desc: '' },
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bag-12.png', title: 'ladies-hand-bag-12', desc: '' },
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bag-13.png', title: 'ladies-hand-bag-13', desc: '' },
      { src: 'IMAGES/BAGS/LB001/ladies-hand-bags-16.png', title: 'ladies-hand-bags-16', desc: '' },
    ],
    ladiesHandbagsLb002: [
      {
        title: 'FOS structured handbag',
        desc: 'Structured trapeze handbag with accent strap. Available in multiple colours.',
        src: 'IMAGES/BAGS/LB002/lb002-01.png',
        variants: [
          { src: 'IMAGES/BAGS/LB002/lb002-01.png', color: 'Red' },
          { src: 'IMAGES/BAGS/LB002/lb002-02.png', color: 'Black' },
        ],
      },
    ],
    classicTotes: [
      { src: 'IMAGES/BAGS/CLASSIC TOTES/ladies-hand-bag-4.png', title: 'ladies-hand-bag-4', desc: '' },
      { src: 'IMAGES/BAGS/CLASSIC TOTES/ladies-hand-bag-5.png', title: 'ladies-hand-bag-5', desc: '' },
      { src: 'IMAGES/BAGS/CLASSIC TOTES/ladies-hand-bag-6.png', title: 'ladies-hand-bag-6', desc: '' },
    ],
    toteBucketBags: [
      {
        title: 'FOS tote bucket bag',
        desc: 'Everyday tote with bucket silhouette. Available in multiple colours.',
        src: 'IMAGES/BAGS/TOTE BUCKET BAGS/tote-bucket-bags-01.png',
        variants: [
          { src: 'IMAGES/BAGS/TOTE BUCKET BAGS/tote-bucket-bags-01.png', color: 'Black' },
          { src: 'IMAGES/BAGS/TOTE BUCKET BAGS/tote-bucket-bags-02.png', color: 'Brown' },
        ],
      },
    ],
    toteSquareBags: [
      {
        title: 'FOS square tote',
        desc: 'Front-zip square tote for work and travel. Available in multiple colours.',
        src: 'IMAGES/BAGS/TOTE SQUARE BAGS/tote-square-1.png',
        variants: [
          { src: 'IMAGES/BAGS/TOTE SQUARE BAGS/tote-square-1.png', color: 'Black' },
          { src: 'IMAGES/BAGS/TOTE SQUARE BAGS/tote-square-2.png', color: 'Brown' },
        ],
      },
    ],
    monkeyBags: [
      {
        title: 'FOS mini backpack',
        desc: 'Compact everyday backpack. Available in multiple colours.',
        src: 'IMAGES/BAGS/MONKEY BAGS/b1.png',
        variants: [
          { src: 'IMAGES/BAGS/MONKEY BAGS/b1.png', color: 'Black' },
          { src: 'IMAGES/BAGS/MONKEY BAGS/b2.png', color: 'Brown' },
          { src: 'IMAGES/BAGS/MONKEY BAGS/b3.png', color: 'Taupe' },
          { src: 'IMAGES/BAGS/MONKEY BAGS/b4.png', color: 'Mauve' },
        ],
      },
    ],
    slingBags: [
      { src: 'IMAGES/BAGS/SLING BAGS/sling-bag-1.png', title: 'sling-bag-1', desc: '' },
      { src: 'IMAGES/BAGS/SLING BAGS/sling-bag-2.png', title: 'sling-bag-2', desc: '' },
      { src: 'IMAGES/BAGS/SLING BAGS/sling-bag-4.png', title: 'sling-bag-4', desc: '' },
      { src: 'IMAGES/BAGS/SLING BAGS/sling-bag-5.png', title: 'sling-bag-5', desc: '' },
    ],
    manBags: [
      { src: 'IMAGES/BAGS/MANBAGS/sleek-black-leather-messenger-bag.png', title: 'sleek-black-leather-messenger-bag', desc: '' },
      { src: 'IMAGES/BAGS/MANBAGS/dark-brown-leather-man-bag.png', title: 'dark-brown-leather-man-bag', desc: '' },
      { src: 'IMAGES/BAGS/MANBAGS/chocolate-brown-leather-messenger-bag-1.png', title: 'chocolate-brown-leather-messenger-bag-1', desc: '' },
      { src: 'IMAGES/BAGS/MANBAGS/leather-crossbody-bag-with-brass-details.png', title: 'leather-crossbody-bag-with-brass-details', desc: '' },
    ],
    travellingBags: [
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-1.png', title: 'travelling-bag-1', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-2.png', title: 'travelling-bag-2', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-3.png', title: 'travelling-bag-3', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-4.png', title: 'travelling-bag-4', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-5.png', title: 'travelling-bag-5', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-6.png', title: 'travelling-bag-6', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-7.png', title: 'travelling-bag-7', desc: '' },
      { src: 'IMAGES/BAGS/TRAVELLING BAGS/travelling-bag-8.png', title: 'travelling-bag-8', desc: '' },
    ],
    backpacks: [
      { src: 'IMAGES/BAGS/BACKPACKS/back-pack-1.png', title: 'back-pack-1', desc: '' },
      { src: 'IMAGES/BAGS/BACKPACKS/back-pack-2.png', title: 'back-pack-2', desc: '' },
    ],
    laptopBags: [
      { src: 'IMAGES/BAGS/LAPTOP BAGS/laptop-bag-1.png', title: 'laptop-bag-1', desc: '' },
      { src: 'IMAGES/BAGS/LAPTOP BAGS/laptop-bag-2.png', title: 'laptop-bag-2', desc: '' },
    ],
    documentationBags: [
      { src: 'IMAGES/BAGS/DOCUMENTATION BAGS/documentation-bag-2-1.png', title: 'documentation-bag-2-1', desc: '' },
      { src: 'IMAGES/BAGS/DOCUMENTATION BAGS/documentation-bag-2-2.png', title: 'documentation-bag-2-2', desc: '' },
    ],
  },
};

